name: Deploy Swagger Docs to GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy API Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install redoc-cli
        run: npm install -g redoc-cli

      - name: Build Spring Boot App
        run: |
          ./gradlew bootJar
          java -jar build/libs/*.jar &
          sleep 15

      - name: Download OpenAPI YAML
        run: curl -s http://localhost:8080/v3/api-docs.yaml -o openapi.yaml

      - name: Generate Redoc HTML
        run: |
          mkdir -p docs
          redoc-cli bundle openapi.yaml -o docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
